## Masking invalid entried in numpy

In [1]:
import numpy

In [2]:
testarr = numpy.array([1,2,3,4,numpy.nan,5,6])

In [3]:
testarr

array([ 1.,  2.,  3.,  4., nan,  5.,  6.])

In [4]:
testarr2 = numpy.array([1,2,3,numpy.nan,5,6,7])

In [5]:
testarr2

array([ 1.,  2.,  3., nan,  5.,  6.,  7.])

In [6]:
nanmask = (testarr > 0)

/Users/cv307/anaconda2/envs/astroconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


In [7]:
nanmask

array([ True,  True,  True,  True, False,  True,  True])

In [8]:
testarr[nanmask]

array([1., 2., 3., 4., 5., 6.])

In [9]:
doublemask = (testarr > 0) & (testarr2 > 0)

/Users/cv307/anaconda2/envs/astroconda3/lib/python3.5/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


In [10]:
doublemask

array([ True,  True,  True, False, False,  True,  True])

In [11]:
testarr[doublemask]

array([1., 2., 3., 5., 6.])

In [12]:
testarr2[doublemask]

array([1., 2., 3., 6., 7.])

In [15]:
~numpy.isnan(testarr)

array([ True,  True,  True,  True, False,  True,  True])

In [16]:
nicemask = ~numpy.isnan(testarr) & ~numpy.isnan(testarr2)

In [17]:
nicemask

array([ True,  True,  True, False, False,  True,  True])

~ means is not. 

& means and, | means or, ^ and_or